### ISSUE TITLE
Response code 404 (Error while getting hotspots list) when disabling noSecurityHotspot

### ISSUE THREAD

**Issue by mllamazares** [soprasteria/sonar-report#110]
I generate the reports without errors like this:

```
sonar-report \
  --sonarurl="http://localhost:9000" \
  --sonarcomponent="sopra-steria:soprasteria_sonar-report" \
  --sonarorganization="sopra-steria" \
  --project="pygoat" \
  --sonartoken="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  --application="pygoat" \
  --release="1.0.0" \
  --sinceleakperiod="false" \
  --noSecurityHotspot="true" \
  --allbugs="true" > /tmp/sonar-report_sonar-report.html
```

However, if I set `--noSecurityHotspot="false"` I get the following error:

```
No proxy configuration detected
sonarqube version: 9.4.0.54424
Error while getting hotspots list : ERR_NON_2XX_3XX_RESPONSE - Response code 404 (Not Found) - 404 - Not Found - {"errors":[{"msg":"Project \u0027sopra-steria:soprasteria_sonar-report\u0027 not found"}]}
```

This is how my SonarQube project looks like:
![image](https://user-images.githubusercontent.com/5461023/174046781-e8e43ac6-04e0-494a-8a03-ab1fbb5135a0.png)
![image](https://user-images.githubusercontent.com/5461023/174046844-52b5426d-d8ef-4363-85ae-4aad6a638592.png)

I guess that is because I have set `sinceleakperiod` to false, so it just retrieves the latest snapshot with 0 new hotspots. However, it should not abort the report generation, just display a warning. 

Version info:
* SonarQube: 9.4.0.54424
* Node: v16.15.1
* npm: 8.11.0

**Comment by thecampagnards** [comment]
Are you sure that sonarcomponent is correct for you ?
