### ISSUE TITLE
Error while using 

### ISSUE THREAD

**Issue by ClyviSarahM** [soprasteria/sonar-report#131]
Having an issue while generating sonar report with the option **allbugs** : 
error: unknown option '--allbugs=true'

and the option **--no-security-hotspot** : 
error: unknown option '--no-security-hotspot=true'

The complete code is : 
```
sonar-report \
    --sonartoken="${SONAR_TOKEN}"\
    --sonarurl="${SONAR_URL}" \
    --sonarcomponent="BACKEND" \
    --project="BACKEND" \
    --application="BACKEND" \
    --allbugs="false" \
    --release="${GORO}" > ./sonar-report-backend.html \
    --no-security-hotspot=true \
    --branch="${branch}"
```

**Comment by thecampagnards** [comment]
Hello, no need to add ´=true’ just use ’--no-security-hotspot’ should work
