### ISSUE TITLE
Security Hotspot are not included in the generated report

### ISSUE THREAD

**Issue by shakunahuja** [soprasteria/sonar-report#136]
We are using SonarQube 7.8 ,sonar-report 3.0.3 and node 14.18.1 .we are trying to generate the html report using the steps mentioned but security hotspot information is not there in the report.

**Comment by thecampagnards** [comment]
Hello,
I will try it soon with sonarqube 7.8
Thanks for the issue

**Comment by thecampagnards** [comment]
Fixed in https://github.com/soprasteria/sonar-report/releases/tag/3.0.6
