### ISSUE TITLE
Add branch name in the report output

### ISSUE THREAD

**Issue by mmarcoux09** [soprasteria/sonar-report#140]
Would it be possible to add in the HTML file / In the output the name of the branch that was recovered?
It would help us without renaming the report files in our pipelines.

Thanks

**Comment by thecampagnards** [comment]
Hello Nice idea !
Can you try to do a pr ? If not I can implement this feature but it will take sometimes
Thx !

**Comment by mmarcoux09** [comment]
Here y'a go :) https://github.com/soprasteria/sonar-report/pull/142

**Comment by thecampagnards** [comment]
Thx ! I will release a new version tomorrow
