### ISSUE TITLE
Need better how to run examples and output formats

### ISSUE THREAD

**Issue by davewichers** [soprasteria/sonar-report#149]
When I follow the example instructions on how to run in the README I get zero results in the output, just like the example. I had expected this tool would need access to a sonar.token for the project so it is authorized to use the API to download project results.  But I don't see anything about that. Is this tool only able to access data from publicly accessible projects or something?

Also, HTML isn't the only format people might want. Is there a raw/machine readable results format option? Like JSON, XML, or .csv.  Seems like it should be easy for this tool to support a machine readable output format since it probably gets the results that way from the Sonar API in the first place.

**Comment by thecampagnards** [comment]
Hello,
You can use `--save-report-json example.json` this will give you this kind of output:
```json
{
  "date": "Fri Oct 14 2022",
  "projectName": "Sonar Report",
  "applicationName": "sonar-report",
  "releaseName": "1.0.0",
  "branch": "master",
  "sinceLeakPeriod": false,
  "previousPeriod": "",
  "allBugs": false,
  "fixMissingRule": false,
  "noRulesInReport": true,
  "vulnerabilityPhrase": "Vulnerability",
  "vulnerabilityPluralPhrase": "Vulnerabilities",
  "sonarBaseURL": "https://sonarcloud.io",
  "sonarComponent": "sopra-steria:soprasteria_sonar-report",
  "sonarOrganization": "sopra-steria",
  "rules": {},
  "issues": [],
  "hotspotKeys": [],
  "deltaAnalysis": "No",
  "qualityGateStatus": false,
  "summary": {
    "blocker": 0,
    "critical": 0,
    "major": 0,
    "minor": 0
  }
}
```
