### ISSUE TITLE
Known Security Rules section missing in report

### ISSUE THREAD

**Issue by ctrung** [soprasteria/sonar-report#150]
By default, the "Known Security Rules" section is missing with the latest version 3.0.5. 
Without it, no data is imported in Defect Dojo.

The section was still present in 2.5.0.

**Comment by thecampagnards** [comment]
fixed will be soon available in a new release

**Comment by thecampagnards** [comment]
Available in the https://github.com/soprasteria/sonar-report/releases/tag/3.0.6

**Comment by ctrung** [comment]
Thanks for your hardwork ! 
The section is back with this new release.
