### ISSUE TITLE
Hotspots aren't retrieved from Sonarqube 7.9

### ISSUE THREAD

**Issue by ctrung** [soprasteria/sonar-report#154]
Hi, 

There's a regression in Sonarqube's version detection algorithm when dealing with hotspots retrieval. 

Using Sonarqube 7.9.1 (build 27448) and sonar-report 3.0.6, semver module is not working as intended.

When I add the following debug lines : 
```
  console.error("semver.satisfies(version, \"<7.3\")=%s", semver.satisfies(version, "<7.3"));
  console.error("semver.satisfies(version, \">=7.3 && <7.8\")=%s", semver.satisfies(version, ">=7.3 && <7.8"));
  console.error("semver.satisfies(version, \">=7.8 && <8.2\")=%s", semver.satisfies(version, ">=7.8 && <8.2"));

  console.error("version < \"7.3\"=%s", version < "7.3");
  console.error("version >= \"7.3\" && version < \"7.8\"=%s", version >= "7.3" && version < "7.8");
  console.error("version >= \"7.8\" && version < \"8.2\"=%s", version >= "7.8" && version < "8.2");
```

Here's the output : 
```
sonarqube version: 7.9.1.27448
semver.satisfies(version, "<7.3")=false
semver.satisfies(version, ">=7.3 && <7.8")=false
semver.satisfies(version, ">=7.8 && <8.2")=false
version < "7.3"=false
version >= "7.3" && version < "7.8"=false
version >= "7.8" && version < "8.2"=true
```

Result : execution path is always entering the else clause (https://github.com/soprasteria/sonar-report/blob/master/index.js#L195) and "to review" status hotspots in Sonarqube 7.9.1 are not found in the generated report.

**Comment by thecampagnards** [comment]
Hello,
I released the 3.0.7 I did some tests it look good.
Can you confirm ?

**Comment by ctrung** [comment]
Hi, 

The fix does not work, at least on my instance of SonarQube. As you can see in the logs, mine returned a version of 7.9.1.27448 which does not respect semver convention strictly speaking.

Just made some tests based on what is in `version = json.version` (L.168) : 
- 7.9.1 : `semver.satisfies(version, "7.8 - 8.2")` returns true
- 7.9.1.27448 : `semver.satisfies(version, "7.8 - 8.2")` returns false 😢

**Comment by thecampagnards** [comment]
Hi,
With this version it should be good https://github.com/soprasteria/sonar-report/releases/tag/3.0.8
I used `semver.coerce` to reformat the error:
```js
semver.valid(semver.coerce('42.6.7.9.3-alpha')) // '42.6.7'
```

**Comment by ctrung** [comment]
Thx for your hardwork !
