### ISSUE TITLE
security hotspot new code filter is wrong

### ISSUE THREAD

**Issue by mdavino** [soprasteria/sonar-report#212]
The correct parameter is **inNewCodePeriod** not sinceLeakPeriod.

https://next.sonarqube.com/sonarqube/web_api/api/hotspots/search

**Comment by mdavino** [comment]
For issue, since version 10, parameter 'sinceLeakPeriod' is removed. Repleced by 'inNewCodePeriod'.
https://next.sonarqube.com/sonarqube/web_api/api/issues/search

**Comment by thecampagnards** [comment]
https://github.com/soprasteria/sonar-report/pull/219 merged I will release it soon
