### ISSUE TITLE
sonar-report data is empty. HTML page doesn't show anything about the project issues.

### ISSUE THREAD

**Issue by karthik137** [soprasteria/sonar-report#22]
I want to import sonarqube reports in defectdojo. My Jenkins pipeline has SAST job in which sonarqube scanning is performed. Sonarqube dashboard shows issues and bugs for bodgeit application.

I was using the following command to get the report.

```
sonar-report   --sonarurl="http://<ipaddress>:5000/sonar"   --project="bodgeit"   --application="bodgeit"    --noSecurityHotspot="true"  > /tmp/sonar-report_sonar-report.html
```
The html page does not show anything about bodgeit issues. I am attaching the images. Please guide me. I have to integrate this in the Jenkins pipeline.

![sonar-report-empty](https://user-images.githubusercontent.com/19289544/73119683-6f633c80-3f8b-11ea-8681-d9a15a41129e.png)
![sonar-dashboard](https://user-images.githubusercontent.com/19289544/73119686-74c08700-3f8b-11ea-8665-a51f6cbe9445.png)

Probably i am missing few parameters or the parameters i am passing might be wrong. Help is needed.

**Comment by karthik137** [comment]
Sonarqube version is Version 6.7.6 (build 38781)

**Comment by sulisty0** [comment]
hi, you need to set --sonarcomponent with your project id

**Comment by devsecops19-sec** [comment]
> hi, you need to set --sonarcomponent with your project id

i have tried by passing all parameters but get empty report

**Comment by ptrovatelli** [comment]
hello @karthik137 . 
can you update your question with the full commands with all arguments (in particular sonarcomponent ) 

can you update the screenshot too so that it displays the "key" that is almost visible at the bottom right there in the current screenshot. that key should equal the sonarcomponent  parameter)

**Comment by thecampagnards** [comment]
too old reopen if you still have issues
