### ISSUE TITLE
How to use the sonar-reporter with self-signed sonar-qube

### ISSUE THREAD

**Issue by praveendvd** [soprasteria/sonar-report#46]
![image](https://user-images.githubusercontent.com/45095911/97792741-3d49cf80-1bda-11eb-9c10-a6eb36b4cf70.png)

**I am getting :** 

unable to verify first certificate error 

**Setup:**

sonarqube is infront of nginx reverse proxy

**Comment by ptrovatelli** [comment]
hello @praveendvd . 
have  you tried? 
`export NODE_EXTRA_CA_CERTS=<my_pem_cert>`

it should work at least after https://github.com/soprasteria/sonar-report/pull/48 is merged

**Comment by ptrovatelli** [comment]
@praveendvd can you confirm it works with the latest version and the parameter advised? 
thanks

**Comment by praveendvd** [comment]
Yes closing the issue now
