### ISSUE TITLE
Environment vars `https_proxy` and `no_proxy` are not handled

### ISSUE THREAD

**Issue by christophe226** [soprasteria/sonar-report#58]
For now, `http_proxy` is read and used in index.js but the other 2 standard environment variables `https_proxy` and `no_proxy` are ignored. Depending on your network configuration, those variables might be essential: for instance, if your Sonar URL matches your `no_proxy` regexp, you don't want `http_proxy` value to be used.

**Comment by thecampagnards** [comment]
We can migrate to hpagent when this https://github.com/delvedor/hpagent/issues/35 will be implemented
