### ISSUE TITLE
SonarOrganization error with SonarCloud.io

### ISSUE THREAD

**Issue by mafrigon** [soprasteria/sonar-report#64]
Hello,

I receive the following error (which prevent me to connect), although authentication to SonarCloud.io is successful.

Error while while getting rules :  - Response code 400 (Bad Request) - 400 - Bad Request - {"errors":[{"msg":"The 'organization' parameter is missing"}]}

Regards,
M-A

**Comment by Homopatrol** [comment]
@mafrigon what is the full command you are passing to connect?

**Comment by rafi-fisker** [comment]
Same issue

````sonar-report --sonarurl="https://sonarcloud.io" --sonarorganization="myorg" --sonarcomponent="mycomponent" --sonartoken="mytoken"```

``````````No proxy configuration detected
Error while while getting rules :  - Response code 400 (Bad Request) - 400 - Bad Request - {"errors":[{"msg":"The \u0027organization\u0027 parameter is missing"}]}

**Comment by ptrovatelli** [comment]
hello @mafrigon  @rafi-fisker . 
It seems that the `withOrganization` string is missing in the URL when getting rules

**Comment by dkade** [comment]
Hi guys,

What is the status on this?

**Comment by ptrovatelli** [comment]
hello @mafrigon @b0564914 @dkade @rafi-fisker 
Is this working for you? https://github.com/soprasteria/sonar-report/pull/76/

**Comment by ptrovatelli** [comment]
hello @mafrigon @b0564914 @dkade @rafi-fisker

just merged the fix and published to npmjs. please come back to me if it's not working for you. 
regards
