### ISSUE TITLE
Too much results asked with `allbugs` option

### ISSUE THREAD

**Issue by GaelGirodon** [soprasteria/sonar-report#7]
An error occured trying to generate a report with `allbugs` option enabled (`true`):

```shell
$ sonar-report \
    --sonarurl="[...]" \
    --sonartoken="[...]" \
    --sonarcomponent="[...]" \
    --project="[...]" \
    --application="[...]" \
    --release="[...]" \
    --sinceleakperiod="true" \
    --allbugs="true" > ./sonar-report.html

Server responded to http://[...]/api/rules/search?activation=true&ps=500&p=21 with status code 400:
{"errors":[{"msg":"Can return only the first 10000 results. 10500th result asked."}]}
```

A limit should be set to avoid requesting more than 10000 results.

**SonarQube:** 7.9

**Comment by thecampagnards** [comment]
Error at this line https://github.com/soprasteria/sonar-report/blob/master/index.js#L171 
check the api https://next.sonarqube.com/sonarqube/web_api/api/issues/search

**Comment by ptrovatelli** [comment]
I've added comments in my last commit regarding this issue (https://github.com/soprasteria/sonar-report/pull/20) . I don't have a solution right now. 
```
- {"errors":[{"msg":"Can return only the first 10000 results. 10500th result asked."}]}

This is a limitation in sonarQube API. There is no way around it to date apart from adding limiting filters

Try removing `--allbugs=true` or tune the query in index.js (see /web_api/api/issues under your sonarQube instance)

See also this discussion https://community.sonarsource.com/t/cannot-get-more-than-10000-results-through-web-api/3662/4
```

We could add a parameter to help people filter results. I initially though of the severities but in the security hotspot, vulnerabilities that aren't confirmed don't have a severity so we'll miss them! 
@GaelGirodon  We're open to suggestions :)

**Comment by GaelGirodon** [comment]
Maybe we could add a limit in the loop condition to avoid requesting more than 10000 results:

```diff
- } while (nbResults === pageSize);
+ } while (nbResults === pageSize && page * pageSize <= 10000);
```

With a page size of 500 items, on the 20th page, the request will be done, but not on the 21th page. We should always stop before the "problematic" 21st page (10001-10500th items) if the condition is correct.

(as it is done here: <https://github.com/GaelGirodon/reportmix/blob/master/reportmix/loaders/sonarqube.py#L83>)

By the way, is the original condition (`nbResults === pageSize`) correct? If the last page contains exactly `pageSize` (500) items and the loop requests for one more page, will the API return an error?

**Comment by ptrovatelli** [comment]
@GaelGirodon I think I prefer getting an error than getting a result that seems fine but where bugs are missing without knowing that something went wrong. 
The good approach to me is to add filters to reduce the number of results don't you think? 
If we're not sure of what filter to add, how about a generic filter where anyone can put any condition for the API? 

Another solution yet, if we do want to get all results and to do that transparently for the users, the only solution I see is doing a dichotomic algorithm: we need to find criteria that we can programatically make vary and generate several calls in order to cover the full range of results. 
That will require a bit of research and coding though :)

**Comment by ptrovatelli** [comment]
we could work on the severities (one call for each severity), but then we need another call to get the vulns that don't have any severity. I have seen those for security hotstpot that aren't confirmed, so this kind of filter might work (if there aren't other cases like this one) 
`statuses=TO_REVIEW,IN_REVIEW,REVIEWED`
(see this PR about those issues missing severities: https://github.com/soprasteria/sonar-report/pull/20 )

**Comment by thecampagnards** [comment]
too old reopen if you still have issues
